services:
  solr:
    image: solr:8-slim
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    environment:
      - SOLR_CORE=main_core
      - SOLR_OPTS=-Djetty.host=0.0.0.0
    command:
      - solr-precreate
      - main_core

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    environment:
      - URL=http://solr:8983
      - DATA_PATH=./data
    env_file: ./crawler/.env
    volumes:
      - ./crawler/data:/app/data
    depends_on:
      - solr

  frontend:
    build:
      context: ./search-engine
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL=http://solr:8983
    env_file: ./search-engine/.env.local
    depends_on:
      - solr

volumes:
  solr_data:
